### ISSUE TITLE
Elastic framework and it's tasks has problematic memory defaults

### ISSUE THREAD

**Issue by bergerx** [mesosphere/dcos-commons#908] opened 2017-04-21 13:53 UTC
To make the elastic framework running without regular restarts i had to do these changes: 
- Increased mem for Framework task on marathon from 2G to 3G
- Increased memory of elastic framework using environment values of the framework:
  - PROXYLITE_MEM : 100 --> 200
  - INGEST_NODE_MEM: 1G --> 2G (this change is likely overkill)

Note: this is copied from mesosphere/universe#1104

**Comment by gabrielhartmann** [comment] 2017-04-26 05:10
@loren:  Can you have a look at making the appropriate changes here please?

**Comment by loren** [comment] 2017-04-26 18:26
The memory issue with the scheduler got fixed last week and is just waiting to get released in the next version of the Universe package, probably within a week. You'll actually need less memory, not more. The proxylite restart issue is actually not memory related. It gets restarted whenever the scheduler gets restarted, for whatever reason (config changes as well as OOM). 

I'd like to know more about the ingest RAM issue. Are you able to reproduce it and get the error logs?

**Comment by bergerx** [comment] 2017-05-01 08:29
I experienced the ingester issue on two other clusters as well this week
bit didnt have time ti dig in. We have ~10 agents in the small cluster and
filebeat pushing task logs to ingester vip. I'm not sure if i can try to
dive in and see what the problem is this week.

**Comment by loren** [comment] 2017-05-01 16:05
I'm happy to look into the root cause if you can grab the stdout/stderr task logs the next time you happen to see a failing ingest node.

**Comment by loren** [comment] 2017-05-24 03:10
Fixed in https://github.com/mesosphere/dcos-commons/pull/994

**Closed by loren** 2017-05-24 03:10 UTC
